import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function run(command, args) {
  const result = spawnSync(command, args, { cwd: root, stdio: "inherit" });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

/**
 * The screenshots are generated by `bun run screenshots`, which drives the real
 * demo page — so they drift silently when a tool is renamed or a shot is
 * dropped. Checked here rather than left to a reader finding a broken image.
 */
function checkScreenshots() {
  const shotsDir = resolve(root, "docs/screenshots");
  const available = new Set(
    readdirSync(shotsDir)
      .filter((file) => file.endsWith(".png"))
      .map((file) => file.slice(0, -4)),
  );
  const referenced = new Map();
  const pages = [
    "README.md",
    ...readdirSync(resolve(root, "docs"))
      .filter((file) => file.endsWith(".md"))
      .map((file) => `docs/${file}`),
  ];
  for (const page of pages) {
    const path = resolve(root, page);
    if (!existsSync(path)) continue;
    for (const match of readFileSync(path, "utf8").matchAll(/screenshots\/([\w-]+)\.png/g)) {
      referenced.set(match[1], page);
    }
  }

  const missing = [...referenced].filter(([name]) => !available.has(name));
  if (missing.length > 0) {
    const detail = missing.map(([name, page]) => `${name}.png (${page})`).join(", ");
    throw new Error(`documentation references screenshots that do not exist: ${detail}`);
  }
  const unused = [...available].filter((name) => !referenced.has(name));
  if (unused.length > 0) {
    console.warn(`Unreferenced screenshots (safe to delete): ${unused.join(", ")}`);
  }
  console.log(`Screenshots: ${referenced.size} referenced, all present.`);
}

checkScreenshots();
run("bun", ["run", "build"]);

const publicDir = resolve(root, "docs/public");
const publicDemo = resolve(publicDir, "demo");
const publicDist = resolve(publicDir, "dist");
const publicScreenshots = resolve(publicDir, "screenshots");
rmSync(publicDemo, { recursive: true, force: true });
rmSync(publicDist, { recursive: true, force: true });
rmSync(publicScreenshots, { recursive: true, force: true });
mkdirSync(publicDemo, { recursive: true });
cpSync(resolve(root, "demo/index.html"), resolve(publicDemo, "index.html"));
cpSync(resolve(root, "dist"), publicDist, { recursive: true });
cpSync(resolve(root, "docs/screenshots"), publicScreenshots, { recursive: true });

try {
  run("bunx", ["vitepress", "build", "docs"]);
} finally {
  rmSync(publicDemo, { recursive: true, force: true });
  rmSync(publicDist, { recursive: true, force: true });
  rmSync(publicScreenshots, { recursive: true, force: true });
}

console.log("Documentation site built with the live demo and local package bundle.");
